# Application
base.url=https://opensource-demo.orangehrmlive.com
api.base.url=https://opensource-demo.orangehrmlive.com

# Browser  (chrome / firefox / edge)
browser=chrome
headless=false

# Timeouts (seconds)
implicit.wait=10
explicit.wait=15
page.load.timeout=30

# Reports
report.path=reports/ExtentReport.html
report.title=OrangeHRM Automation Report
report.name=Employee Lifecycle Suite

# Test Data
testdata.path=src/test/resources/testdata/EmployeeData.json
profile.picture.path=src/test/resources/testdata/profile.png
